-- BLACKSY GAME — Supabase production schema and hardening migration
-- Idempotent bootstrap/migration. Run in Supabase Dashboard → SQL Editor.
-- This file intentionally contains no service-role key or user password.

begin;

-- -----------------------------------------------------------------------------
-- 1) Profiles and role protection
-- -----------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text not null default '',
  role text not null default 'customer',
  bio text not null default '',
  avatar_url text not null default '', -- private Storage object path, not a public URL
  phone text not null default '',
  preferred_platform text not null default '',
  default_address text not null default '',
  postal_code text not null default '',
  newsletter_opt_in boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists email text,
  add column if not exists full_name text not null default '',
  add column if not exists role text not null default 'customer',
  add column if not exists bio text not null default '',
  add column if not exists avatar_url text not null default '',
  add column if not exists phone text not null default '',
  add column if not exists preferred_platform text not null default '',
  add column if not exists default_address text not null default '',
  add column if not exists postal_code text not null default '',
  add column if not exists newsletter_opt_in boolean not null default false,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

update public.profiles set role = 'customer' where role is null or role not in ('customer', 'admin');
alter table public.profiles alter column role set default 'customer';
alter table public.profiles alter column role set not null;
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.profiles'::regclass and conname = 'profiles_role_allowed'
  ) then
    alter table public.profiles
      add constraint profiles_role_allowed check (role in ('customer', 'admin')) not valid;
  end if;
  alter table public.profiles validate constraint profiles_role_allowed;
end $$;

create or replace function public.is_admin_user()
returns boolean
language sql
stable
security definer
set search_path = ''
set row_security = off
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  );
$$;
revoke all on function public.is_admin_user() from public, anon;
grant execute on function public.is_admin_user() to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    'customer'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;
revoke all on function public.handle_new_user() from public, anon, authenticated;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Backfill existing Auth users without changing any existing role.
insert into public.profiles (id, email, full_name, role)
select u.id, u.email, coalesce(u.raw_user_meta_data ->> 'full_name', ''), 'customer'
from auth.users u
on conflict (id) do nothing;

-- -----------------------------------------------------------------------------
-- 2) Products catalog
-- -----------------------------------------------------------------------------
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  sku text,
  name text not null,
  slug text,
  category text not null default 'بازی',
  cat text not null default 'بازی',
  kind text not null default 'بازی',
  brand text not null default 'Blacksy Game',
  model text not null default '',
  short_description text not null default '',
  description text not null default '',
  specifications jsonb not null default '{}'::jsonb,
  price bigint,
  old bigint,
  stock integer,
  art text not null default '',
  image_url text not null default '',
  images jsonb not null default '[]'::jsonb,
  platforms jsonb not null default '[]'::jsonb,
  source text not null default 'فروشگاه بلکسی گیم',
  source_url text not null default '',
  price_source_url text not null default '',
  checked_at text not null default '',
  status text not null default 'active',
  featured boolean not null default false,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products
  add column if not exists sku text,
  add column if not exists name text not null default '',
  add column if not exists slug text,
  add column if not exists category text not null default 'بازی',
  add column if not exists cat text not null default 'بازی',
  add column if not exists kind text not null default 'بازی',
  add column if not exists brand text not null default 'Blacksy Game',
  add column if not exists model text not null default '',
  add column if not exists short_description text not null default '',
  add column if not exists description text not null default '',
  add column if not exists specifications jsonb not null default '{}'::jsonb,
  add column if not exists price bigint,
  add column if not exists old bigint,
  add column if not exists stock integer,
  add column if not exists art text not null default '',
  add column if not exists image_url text not null default '',
  add column if not exists images jsonb not null default '[]'::jsonb,
  add column if not exists platforms jsonb not null default '[]'::jsonb,
  add column if not exists source text not null default 'فروشگاه بلکسی گیم',
  add column if not exists source_url text not null default '',
  add column if not exists price_source_url text not null default '',
  add column if not exists checked_at text not null default '',
  add column if not exists status text not null default 'active',
  add column if not exists featured boolean not null default false,
  add column if not exists is_published boolean not null default true,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

update public.products set price = null where price < 0;
update public.products set old = null where old < 0;
update public.products set stock = 0 where stock < 0;
do $$
begin
  if not exists (select 1 from pg_constraint where conrelid='public.products'::regclass and conname='products_price_nonnegative') then
    alter table public.products add constraint products_price_nonnegative check (price is null or price >= 0) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conrelid='public.products'::regclass and conname='products_old_price_nonnegative') then
    alter table public.products add constraint products_old_price_nonnegative check (old is null or old >= 0) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conrelid='public.products'::regclass and conname='products_stock_nonnegative') then
    alter table public.products add constraint products_stock_nonnegative check (stock is null or stock >= 0) not valid;
  end if;
  alter table public.products validate constraint products_price_nonnegative;
  alter table public.products validate constraint products_old_price_nonnegative;
  alter table public.products validate constraint products_stock_nonnegative;
end $$;

-- -----------------------------------------------------------------------------
-- 3) Orders. Clients cannot insert or set totals/status directly.
-- -----------------------------------------------------------------------------
create table if not exists public.orders (
  id uuid primary key default pg_catalog.gen_random_uuid(),
  order_code text not null,
  user_id uuid references auth.users(id) on delete set null,
  customer_name text not null,
  customer_phone text not null,
  address text not null,
  postal_code text not null default '',
  shipping_method text not null default 'ارسال بلکسی گیم — رایگان',
  payment_method text not null default 'پرداخت اینترنتی',
  status text not null default 'pending',
  total_amount bigint not null default 0,
  items jsonb not null default '[]'::jsonb,
  guest_token_hash text,
  inventory_reserved boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders
  add column if not exists order_code text,
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists customer_name text not null default '',
  add column if not exists customer_phone text not null default '',
  add column if not exists address text not null default '',
  add column if not exists postal_code text not null default '',
  add column if not exists shipping_method text not null default 'ارسال بلکسی گیم — رایگان',
  add column if not exists payment_method text not null default 'پرداخت اینترنتی',
  add column if not exists status text not null default 'pending',
  add column if not exists total_amount bigint not null default 0,
  add column if not exists items jsonb not null default '[]'::jsonb,
  add column if not exists guest_token_hash text,
  add column if not exists inventory_reserved boolean not null default false,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

update public.orders
set order_code = 'BG-LEGACY-' || left(replace(id::text, '-', ''), 12)
where order_code is null or btrim(order_code) = '';
update public.orders set status = 'pending'
where status is null or status not in ('pending', 'processing', 'shipped', 'delivered', 'cancelled');
do $$
begin
  if not exists (select 1 from pg_constraint where conrelid='public.orders'::regclass and conname='orders_status_allowed') then
    alter table public.orders add constraint orders_status_allowed check (status in ('pending','processing','shipped','delivered','cancelled')) not valid;
  end if;
  alter table public.orders validate constraint orders_status_allowed;
end $$;
alter table public.orders alter column order_code set not null;
create unique index if not exists orders_order_code_unique on public.orders(order_code);
create index if not exists orders_user_created_idx on public.orders(user_id, created_at desc);

-- -----------------------------------------------------------------------------
-- 4) Support conversations. Guest access is only through token-checked RPCs.
--    The table is never directly readable/writable by anon or customers.
-- -----------------------------------------------------------------------------
create table if not exists public.support_threads (
  thread_id text primary key,
  user_id uuid references auth.users(id) on delete set null,
  customer_name text not null default 'کاربر بلکسی گیم',
  customer_contact text not null default '',
  status text not null default 'open',
  messages jsonb not null default '[]'::jsonb,
  guest_token_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.support_threads
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists customer_name text not null default 'کاربر بلکسی گیم',
  add column if not exists customer_contact text not null default '',
  add column if not exists status text not null default 'open',
  add column if not exists messages jsonb not null default '[]'::jsonb,
  add column if not exists guest_token_hash text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

update public.support_threads set status = 'open'
where status is null or status not in ('open', 'answered', 'closed');
alter table public.support_threads alter column status set default 'open';
alter table public.support_threads alter column status set not null;
do $$
begin
  if not exists (select 1 from pg_constraint where conrelid='public.support_threads'::regclass and conname='support_threads_status_allowed') then
    alter table public.support_threads add constraint support_threads_status_allowed check (status in ('open','answered','closed')) not valid;
  end if;
  alter table public.support_threads validate constraint support_threads_status_allowed;
end $$;
create index if not exists support_threads_updated_idx on public.support_threads(updated_at desc);

-- -----------------------------------------------------------------------------
-- 5) Homepage content: public read, admin-only write.
-- -----------------------------------------------------------------------------
create table if not exists public.site_content (
  id text primary key check (id = 'home'),
  content jsonb not null default '{"slides":[],"showcases":[]}'::jsonb,
  updated_at timestamptz not null default now()
);
insert into public.site_content (id, content)
values ('home', '{"slides":[],"showcases":[]}'::jsonb)
on conflict (id) do nothing;

-- -----------------------------------------------------------------------------
-- 6) Updated-at trigger
-- -----------------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;
revoke all on function public.touch_updated_at() from public, anon, authenticated;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at before update on public.profiles
for each row execute function public.touch_updated_at();
drop trigger if exists products_touch_updated_at on public.products;
create trigger products_touch_updated_at before update on public.products
for each row execute function public.touch_updated_at();
drop trigger if exists orders_touch_updated_at on public.orders;
create trigger orders_touch_updated_at before update on public.orders
for each row execute function public.touch_updated_at();

create or replace function public.release_order_inventory()
returns trigger
language plpgsql
security definer
set search_path = ''
set row_security = off
as $$
declare
  v_items jsonb;
  v_line jsonb;
  v_product_id bigint;
  v_quantity integer;
  v_release boolean := false;
begin
  if tg_op = 'DELETE' then
    v_items := old.items;
    v_release := old.inventory_reserved and old.status in ('pending', 'processing');
  else
    if old.status = 'cancelled' and new.status <> 'cancelled' then
      raise exception 'سفارش لغوشده را نمی‌توان دوباره فعال کرد';
    end if;
    if old.status <> 'cancelled' and new.status = 'cancelled' then
      v_items := old.items;
      v_release := old.inventory_reserved and old.status in ('pending', 'processing');
      new.inventory_reserved := false;
    end if;
  end if;

  if v_release and pg_catalog.jsonb_typeof(v_items) = 'array' then
    for v_line in select value from pg_catalog.jsonb_array_elements(v_items) as e(value) loop
      v_product_id := (v_line ->> 'id')::bigint;
      v_quantity := (v_line ->> 'qty')::integer;
      if v_product_id > 0 and v_quantity > 0 then
        update public.products
        set stock = stock + v_quantity
        where id = v_product_id and stock is not null;
      end if;
    end loop;
  end if;

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;
revoke all on function public.release_order_inventory() from public, anon, authenticated;
drop trigger if exists orders_release_inventory on public.orders;
create trigger orders_release_inventory
before update of status or delete on public.orders
for each row execute function public.release_order_inventory();
drop trigger if exists support_threads_touch_updated_at on public.support_threads;
create trigger support_threads_touch_updated_at before update on public.support_threads
for each row execute function public.touch_updated_at();
drop trigger if exists site_content_touch_updated_at on public.site_content;
create trigger site_content_touch_updated_at before update on public.site_content
for each row execute function public.touch_updated_at();

-- Drop all old policies on these app tables; the policies below are the only ones used.
do $$
declare p record;
begin
  for p in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in ('profiles', 'products', 'orders', 'support_threads', 'site_content')
  loop
    execute format('drop policy %I on %I.%I', p.policyname, p.schemaname, p.tablename);
  end loop;
end $$;

-- -----------------------------------------------------------------------------
-- 7) Row-level security and least-privilege grants
-- -----------------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.support_threads enable row level security;
alter table public.site_content enable row level security;

revoke all on table public.profiles from public, anon, authenticated;
revoke all on table public.products from public, anon, authenticated;
revoke all on table public.orders from public, anon, authenticated;
revoke all on table public.support_threads from public, anon, authenticated;
revoke all on table public.site_content from public, anon, authenticated;

-- Profiles: customers can see/update their own allowed fields. Role/email are not client-writable.
grant select on public.profiles to authenticated;
grant update (full_name, bio, avatar_url, phone, preferred_platform, default_address, postal_code, newsletter_opt_in, updated_at)
  on public.profiles to authenticated;
create policy profiles_select_own on public.profiles for select to authenticated
  using (auth.uid() = id);
create policy profiles_select_admin on public.profiles for select to authenticated
  using (public.is_admin_user());
create policy profiles_update_own on public.profiles for update to authenticated
  using (auth.uid() = id) with check (auth.uid() = id);

-- Products: public catalog reads only published rows; only admins can write.
grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;
create policy products_public_read on public.products for select to anon, authenticated
  using (is_published = true);
create policy products_admin_read on public.products for select to authenticated
  using (public.is_admin_user());
create policy products_admin_insert on public.products for insert to authenticated
  with check (public.is_admin_user());
create policy products_admin_update on public.products for update to authenticated
  using (public.is_admin_user()) with check (public.is_admin_user());
create policy products_admin_delete on public.products for delete to authenticated
  using (public.is_admin_user());

-- Orders: no direct client INSERT. A database function validates product IDs/prices and computes totals.
grant select, delete on public.orders to authenticated;
grant update (status) on public.orders to authenticated;
create policy orders_select_owner on public.orders for select to authenticated
  using (auth.uid() = user_id);
create policy orders_select_admin on public.orders for select to authenticated
  using (public.is_admin_user());
create policy orders_admin_update on public.orders for update to authenticated
  using (public.is_admin_user()) with check (public.is_admin_user());
create policy orders_admin_delete on public.orders for delete to authenticated
  using (public.is_admin_user());

-- Support: only authenticated admins can query/delete rows directly; all customer access is token-checked RPC.
grant select, delete on public.support_threads to authenticated;
create policy support_admin_read on public.support_threads for select to authenticated
  using (public.is_admin_user());
create policy support_admin_delete on public.support_threads for delete to authenticated
  using (public.is_admin_user());

-- Homepage content is public-readable and admin-writable.
grant select on public.site_content to anon, authenticated;
grant insert, update, delete on public.site_content to authenticated;
create policy site_content_public_read on public.site_content for select to anon, authenticated
  using (true);
create policy site_content_admin_insert on public.site_content for insert to authenticated
  with check (public.is_admin_user());
create policy site_content_admin_update on public.site_content for update to authenticated
  using (public.is_admin_user()) with check (public.is_admin_user());
create policy site_content_admin_delete on public.site_content for delete to authenticated
  using (public.is_admin_user());

-- -----------------------------------------------------------------------------
-- 8) Secure order RPCs
-- -----------------------------------------------------------------------------
-- Hash 256-bit, lower-case hex bearer secrets inside PostgreSQL. RPC callers
-- never pass a reusable database hash; only the raw secret crosses TLS and the
-- stored capability remains non-replayable if the table is exposed.
create or replace function public.hash_guest_secret(p_secret text)
returns text
language sql
immutable
set search_path = ''
as $$
  select case
    when coalesce(p_secret, '') ~ '^[0-9a-f]{64}$'
      then pg_catalog.encode(pg_catalog.sha256(pg_catalog.decode(p_secret, 'hex')), 'hex')
    else null
  end;
$$;
revoke all on function public.hash_guest_secret(text) from public, anon, authenticated;

drop function if exists public.create_order(text, text, text, text, text, text, jsonb, text);
create function public.create_order(
  p_customer_name text,
  p_customer_phone text,
  p_address text,
  p_postal_code text,
  p_shipping_method text,
  p_payment_method text,
  p_items jsonb,
  p_guest_secret text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
set row_security = off
as $$
declare
  v_user_id uuid := auth.uid();
  v_order_id uuid := pg_catalog.gen_random_uuid();
  v_order_code text := 'BG-' || upper(left(replace(pg_catalog.gen_random_uuid()::text, '-', ''), 16));
  v_line jsonb;
  v_product public.products%rowtype;
  v_product_id bigint;
  v_quantity integer;
  v_total bigint := 0;
  v_snapshot jsonb := '[]'::jsonb;
  v_guest_hash text;
  v_reserves_stock boolean := false;
  v_result jsonb;
begin
  if length(btrim(coalesce(p_customer_name, ''))) < 2 or length(p_customer_name) > 100 then
    raise exception 'نام گیرنده معتبر نیست';
  end if;
  if length(btrim(coalesce(p_customer_phone, ''))) < 6 or length(p_customer_phone) > 24 then
    raise exception 'شماره تماس معتبر نیست';
  end if;
  if length(btrim(coalesce(p_address, ''))) < 5 or length(p_address) > 500 then
    raise exception 'نشانی معتبر نیست';
  end if;
  if length(coalesce(p_postal_code, '')) > 16 then
    raise exception 'کد پستی معتبر نیست';
  end if;
  if length(coalesce(p_shipping_method, '')) > 100 or length(coalesce(p_payment_method, '')) > 60 then
    raise exception 'روش ارسال یا پرداخت معتبر نیست';
  end if;
  if coalesce(nullif(btrim(p_shipping_method), ''), 'ارسال بلکسی گیم — رایگان') not in ('ارسال بلکسی گیم — رایگان', 'ارسال سریع') then
    raise exception 'روش ارسال معتبر نیست';
  end if;
  if coalesce(nullif(btrim(p_payment_method), ''), 'پرداخت اینترنتی') not in ('پرداخت اینترنتی', 'پرداخت در محل') then
    raise exception 'روش پرداخت معتبر نیست';
  end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) < 1 or jsonb_array_length(p_items) > 30 then
    raise exception 'اقلام سفارش معتبر نیستند';
  end if;

  if v_user_id is null then
    if coalesce(p_guest_secret, '') !~ '^[0-9a-f]{64}$' then
      raise exception 'توکن سفارش مهمان معتبر نیست';
    end if;
    v_guest_hash := public.hash_guest_secret(p_guest_secret);
  else
    v_guest_hash := null;
  end if;

  for v_line in select value from jsonb_array_elements(p_items) as e(value) loop
    begin
      v_product_id := (v_line ->> 'id')::bigint;
      v_quantity := (v_line ->> 'qty')::integer;
    exception when others then
      raise exception 'شناسه یا تعداد محصول معتبر نیست';
    end;
    if v_quantity < 1 or v_quantity > 20 then
      raise exception 'تعداد هر کالا باید بین ۱ و ۲۰ باشد';
    end if;
    if exists (
      select 1 from pg_catalog.jsonb_array_elements(v_snapshot) as saved(value)
      where (saved.value ->> 'id')::bigint = v_product_id
    ) then
      raise exception 'هر کالا باید فقط یک‌بار در سبد سفارش فرستاده شود';
    end if;

    select * into v_product
    from public.products p
    where p.id = v_product_id and p.is_published = true and p.price is not null and p.price > 0
    for update;
    if not found then
      raise exception 'یکی از کالاها موجود نیست یا قیمت آن تأیید نشده است';
    end if;
    if v_product.stock is not null and v_product.stock < v_quantity then
      raise exception 'موجودی یکی از کالاها کافی نیست';
    end if;
    if v_product.stock is not null then
      update public.products
      set stock = stock - v_quantity
      where id = v_product.id and stock >= v_quantity;
      if not found then raise exception 'موجودی یکی از کالاها کافی نیست'; end if;
      v_reserves_stock := true;
    end if;

    v_total := v_total + (v_product.price * v_quantity);
    v_snapshot := v_snapshot || jsonb_build_array(jsonb_build_object(
      'id', v_product.id,
      'name', v_product.name,
      'qty', v_quantity,
      'price', v_product.price
    ));
  end loop;

  insert into public.orders (
    id, order_code, user_id, customer_name, customer_phone, address, postal_code,
    shipping_method, payment_method, status, total_amount, items, guest_token_hash, inventory_reserved
  ) values (
    v_order_id, v_order_code, v_user_id, btrim(p_customer_name), btrim(p_customer_phone),
    btrim(p_address), btrim(coalesce(p_postal_code, '')),
    coalesce(nullif(btrim(p_shipping_method), ''), 'ارسال بلکسی گیم — رایگان'),
    coalesce(nullif(btrim(p_payment_method), ''), 'پرداخت اینترنتی'),
    'pending', v_total, v_snapshot, v_guest_hash, v_reserves_stock
  );

  select jsonb_build_object(
    'id', v_order_id,
    'order_code', v_order_code,
    'status', 'pending',
    'total_amount', v_total,
    'items', v_snapshot,
    'created_at', now()
  ) into v_result;
  return v_result;
end;
$$;
revoke all on function public.create_order(text, text, text, text, text, text, jsonb, text) from public, anon, authenticated;
grant execute on function public.create_order(text, text, text, text, text, text, jsonb, text) to anon, authenticated;

drop function if exists public.get_guest_order_status(text, text);
create function public.get_guest_order_status(p_order_code text, p_secret text)
returns jsonb
language sql
stable
security definer
set search_path = ''
set row_security = off
as $$
  select jsonb_build_object(
    'order_code', o.order_code,
    'status', o.status,
    'total_amount', o.total_amount,
    'items', o.items,
    'created_at', o.created_at
  )
  from public.orders o
  where o.order_code = upper(btrim(p_order_code))
    and o.guest_token_hash = public.hash_guest_secret(p_secret)
    and o.user_id is null
    and p_secret ~ '^[0-9a-f]{64}$'
  limit 1;
$$;
revoke all on function public.get_guest_order_status(text, text) from public, anon, authenticated;
grant execute on function public.get_guest_order_status(text, text) to anon, authenticated;

-- Admin role changes are possible only through this server-side checked function.
create or replace function public.admin_set_user_role(p_user_id uuid, p_role text)
returns boolean
language plpgsql
security definer
set search_path = ''
set row_security = off
as $$
begin
  if not public.is_admin_user() then
    raise exception 'اجازه دسترسی مدیر لازم است' using errcode = '42501';
  end if;
  if p_role not in ('customer', 'admin') then
    raise exception 'نقش کاربری معتبر نیست';
  end if;
  if p_user_id = auth.uid() and p_role <> 'admin' then
    raise exception 'نمی‌توان نقش حساب مدیر واردشده را حذف کرد';
  end if;
  update public.profiles set role = p_role where id = p_user_id;
  return found;
end;
$$;
revoke all on function public.admin_set_user_role(uuid, text) from public, anon, authenticated;
grant execute on function public.admin_set_user_role(uuid, text) to authenticated;

-- -----------------------------------------------------------------------------
-- 9) Token-protected support RPCs + safe Realtime broadcast pings
-- -----------------------------------------------------------------------------
drop function if exists public.get_support_thread(text, text);
create function public.get_support_thread(p_thread_id text, p_secret text)
returns jsonb
language sql
stable
security definer
set search_path = ''
set row_security = off
as $$
  select jsonb_build_object(
    'thread_id', t.thread_id,
    'customer_name', t.customer_name,
    'customer_contact', t.customer_contact,
    'status', t.status,
    'messages', t.messages,
    'updated_at', t.updated_at
  )
  from public.support_threads t
  where t.thread_id = p_thread_id
    and t.guest_token_hash = public.hash_guest_secret(p_secret)
    and p_secret ~ '^[0-9a-f]{64}$'
  limit 1;
$$;
revoke all on function public.get_support_thread(text, text) from public, anon, authenticated;
grant execute on function public.get_support_thread(text, text) to anon, authenticated;

drop function if exists public.submit_support_message(text, text, text, text, text);
create function public.submit_support_message(
  p_thread_id text,
  p_secret text,
  p_customer_name text,
  p_customer_contact text,
  p_text text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
set row_security = off
as $$
declare
  v_thread public.support_threads%rowtype;
  v_message jsonb;
  v_created boolean := false;
  v_count integer;
  v_secret_hash text;
begin
  if coalesce(p_thread_id, '') !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
    raise exception 'شناسه گفتگوی معتبر نیست';
  end if;
  if coalesce(p_secret, '') !~ '^[0-9a-f]{64}$' then
    raise exception 'کلید گفتگوی معتبر نیست';
  end if;
  v_secret_hash := public.hash_guest_secret(p_secret);
  if length(btrim(coalesce(p_text, ''))) < 1 or length(p_text) > 2000 then
    raise exception 'متن پیام باید بین ۱ تا ۲۰۰۰ نویسه باشد';
  end if;
  if length(coalesce(p_customer_name, '')) > 80 or length(coalesce(p_customer_contact, '')) > 120 then
    raise exception 'اطلاعات تماس معتبر نیست';
  end if;

  v_message := jsonb_build_object(
    'sender', 'customer',
    'text', btrim(p_text),
    'time', to_char(now() at time zone 'Asia/Tehran', 'HH24:MI'),
    'created_at', to_char(now() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
  );

  select * into v_thread
  from public.support_threads t
  where t.thread_id = p_thread_id
  for update;

  if not found then
    insert into public.support_threads (
      thread_id, user_id, customer_name, customer_contact, status, messages, guest_token_hash
    ) values (
      p_thread_id, auth.uid(), coalesce(nullif(btrim(p_customer_name), ''), 'کاربر بلکسی گیم'),
      btrim(coalesce(p_customer_contact, '')), 'open', jsonb_build_array(v_message), v_secret_hash
    ) on conflict (thread_id) do nothing;
    get diagnostics v_count = row_count;
    v_created := (v_count = 1);
    select * into v_thread from public.support_threads t where t.thread_id = p_thread_id for update;
  end if;

  if v_thread.thread_id is null or v_thread.guest_token_hash is distinct from v_secret_hash then
    raise exception 'گفتگو پیدا نشد یا کلید گفتگو نادرست است' using errcode = '42501';
  end if;
  if v_thread.status = 'closed' then
    raise exception 'این گفتگو بسته شده است';
  end if;

  if not v_created then
    if jsonb_array_length(coalesce(v_thread.messages, '[]'::jsonb)) >= 500 then
      raise exception 'ظرفیت این گفتگو تکمیل شده است';
    end if;
    update public.support_threads
    set messages = coalesce(messages, '[]'::jsonb) || jsonb_build_array(v_message),
        status = 'open', updated_at = now()
    where thread_id = p_thread_id
    returning * into v_thread;
  end if;

  return jsonb_build_object(
    'thread_id', v_thread.thread_id,
    'customer_name', v_thread.customer_name,
    'customer_contact', v_thread.customer_contact,
    'status', v_thread.status,
    'messages', v_thread.messages,
    'updated_at', v_thread.updated_at
  );
end;
$$;
revoke all on function public.submit_support_message(text, text, text, text, text) from public, anon, authenticated;
grant execute on function public.submit_support_message(text, text, text, text, text) to anon, authenticated;

create or replace function public.admin_send_support_reply(p_thread_id text, p_text text)
returns jsonb
language plpgsql
security definer
set search_path = ''
set row_security = off
as $$
declare
  v_thread public.support_threads%rowtype;
  v_message jsonb;
begin
  if not public.is_admin_user() then
    raise exception 'اجازه دسترسی مدیر لازم است' using errcode = '42501';
  end if;
  if length(btrim(coalesce(p_text, ''))) < 1 or length(p_text) > 2000 then
    raise exception 'متن پاسخ باید بین ۱ تا ۲۰۰۰ نویسه باشد';
  end if;

  v_message := jsonb_build_object(
    'sender', 'admin',
    'text', btrim(p_text),
    'time', to_char(now() at time zone 'Asia/Tehran', 'HH24:MI'),
    'created_at', to_char(now() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
  );
  update public.support_threads
  set messages = coalesce(messages, '[]'::jsonb) || jsonb_build_array(v_message),
      status = 'answered', updated_at = now()
  where thread_id = p_thread_id
  returning * into v_thread;
  if not found then raise exception 'گفتگو پیدا نشد'; end if;

  return jsonb_build_object(
    'thread_id', v_thread.thread_id,
    'status', v_thread.status,
    'messages', v_thread.messages,
    'updated_at', v_thread.updated_at
  );
end;
$$;
revoke all on function public.admin_send_support_reply(text, text) from public, anon, authenticated;
grant execute on function public.admin_send_support_reply(text, text) to authenticated;

create or replace function public.broadcast_support_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_thread_id text;
begin
  if tg_op = 'DELETE' then
    v_thread_id := old.thread_id;
  else
    v_thread_id := new.thread_id;
  end if;
  -- The public payload is only a wake-up ping. It never contains a message,
  -- contact detail, token hash, or other row data. The guest must re-auth via RPC.
  begin
    perform realtime.send(
      jsonb_build_object('changed', true),
      'support_changed',
      'support:' || v_thread_id,
      false
    );
  exception when others then
    -- Do not fail a support message if today's Realtime partition is unavailable.
    null;
  end;
  return null;
end;
$$;
revoke all on function public.broadcast_support_change() from public, anon, authenticated;
drop trigger if exists support_thread_broadcast on public.support_threads;
create trigger support_thread_broadcast
after insert or update or delete on public.support_threads
for each row execute function public.broadcast_support_change();

-- Publish support table changes to authenticated admins using Postgres Changes.
alter table public.support_threads replica identity full;
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public' and tablename = 'support_threads'
     ) then
    execute 'alter publication supabase_realtime add table public.support_threads';
  end if;
end $$;
alter table public.orders replica identity full;
alter table public.site_content replica identity full;
alter table public.products replica identity full;
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='orders') then
      execute 'alter publication supabase_realtime add table public.orders';
    end if;
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='site_content') then
      execute 'alter publication supabase_realtime add table public.site_content';
    end if;
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='products') then
      execute 'alter publication supabase_realtime add table public.products';
    end if;
  end if;
end $$;

-- Guests can subscribe only to the support broadcast namespace. Broadcast
-- payloads carry no private data; thread ids are random UUIDs and reads still
-- require the per-thread secret hash in get_support_thread().
do $$
declare p record;
begin
  for p in
    select policyname from pg_policies
    where schemaname = 'realtime' and tablename = 'messages'
      and policyname = 'blacksy_public_support_pings'
  loop
    execute format('drop policy %I on realtime.messages', p.policyname);
  end loop;
end $$;
create policy blacksy_public_support_pings on realtime.messages
for select to anon, authenticated
using (extension = 'broadcast' and realtime.topic() like 'support:%');

-- -----------------------------------------------------------------------------
-- 10) Private profile photos and public product image bucket
-- -----------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', false, 1048576, array['image/webp', 'image/jpeg', 'image/png'])
on conflict (id) do update set
  public = false,
  file_size_limit = 1048576,
  allowed_mime_types = array['image/webp', 'image/jpeg', 'image/png'];

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-assets', 'product-assets', true, 5242880, array['image/webp', 'image/jpeg', 'image/png'])
on conflict (id) do update set
  public = true,
  file_size_limit = 5242880,
  allowed_mime_types = array['image/webp', 'image/jpeg', 'image/png'];

-- Remove earlier broad avatar policies, including the formerly public-read rule.
do $$
declare p record;
begin
  for p in
    select policyname from pg_policies
    where schemaname = 'storage' and tablename = 'objects'
      and (
        coalesce(qual, '') ilike '%avatars%'
        or coalesce(with_check, '') ilike '%avatars%'
        or coalesce(qual, '') ilike '%product-assets%'
        or coalesce(with_check, '') ilike '%product-assets%'
        or policyname ilike '%avatar%'
        or policyname ilike '%product-assets%'
        or policyname ilike '%product_assets%'
      )
  loop
    execute format('drop policy %I on storage.objects', p.policyname);
  end loop;
end $$;

create policy blacksy_avatar_read_owner on storage.objects
for select to authenticated
using (
  bucket_id = 'avatars'
  and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin_user())
);
create policy blacksy_avatar_insert_owner on storage.objects
for insert to authenticated
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy blacksy_avatar_update_owner on storage.objects
for update to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy blacksy_avatar_delete_owner on storage.objects
for delete to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

create policy blacksy_product_assets_public_read on storage.objects
for select to anon, authenticated
using (bucket_id = 'product-assets');
create policy blacksy_product_assets_admin_insert on storage.objects
for insert to authenticated
with check (bucket_id = 'product-assets' and public.is_admin_user());
create policy blacksy_product_assets_admin_update on storage.objects
for update to authenticated
using (bucket_id = 'product-assets' and public.is_admin_user())
with check (bucket_id = 'product-assets' and public.is_admin_user());
create policy blacksy_product_assets_admin_delete on storage.objects
for delete to authenticated
using (bucket_id = 'product-assets' and public.is_admin_user());

commit;

-- ADMIN BOOTSTRAP (run manually after the admin account has been created in
-- Supabase Auth → Users; never put its password or a service-role key in JS):
-- update public.profiles set role = 'admin' where email = 'admin@blakci.ir';
-- The admin login screen accepts `blakci_admin` as an alias for this email.
